"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_proof import IndyProof
from openapi_client.model.indy_proof_request import IndyProofRequest
from openapi_client.model.presentation_proposal import PresentationProposal
from openapi_client.model.presentation_request import PresentationRequest
globals()['IndyProof'] = IndyProof
globals()['IndyProofRequest'] = IndyProofRequest
globals()['PresentationProposal'] = PresentationProposal
globals()['PresentationRequest'] = PresentationRequest
from openapi_client.model.v10_presentation_exchange import V10PresentationExchange


class TestV10PresentationExchange(unittest.TestCase):
    """V10PresentationExchange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10PresentationExchange(self):
        """Test V10PresentationExchange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10PresentationExchange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
