"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ld_proof_vc_detail import LDProofVCDetail
from openapi_client.model.v20_cred_filter_indy import V20CredFilterIndy
globals()['LDProofVCDetail'] = LDProofVCDetail
globals()['V20CredFilterIndy'] = V20CredFilterIndy
from openapi_client.model.v20_cred_filter import V20CredFilter


class TestV20CredFilter(unittest.TestCase):
    """V20CredFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredFilter(self):
        """Test V20CredFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
