"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.generated import Generated


class TestGenerated(unittest.TestCase):
    """Generated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenerated(self):
        """Test Generated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Generated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
