"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_cred_filter import V20CredFilter
from openapi_client.model.v20_cred_preview import V20CredPreview
globals()['V20CredFilter'] = V20CredFilter
globals()['V20CredPreview'] = V20CredPreview
from openapi_client.model.v20_cred_bound_offer_request import V20CredBoundOfferRequest


class TestV20CredBoundOfferRequest(unittest.TestCase):
    """V20CredBoundOfferRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredBoundOfferRequest(self):
        """Test V20CredBoundOfferRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredBoundOfferRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
