"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.endorse_transaction_api import EndorseTransactionApi  # noqa: E501


class TestEndorseTransactionApi(unittest.TestCase):
    """EndorseTransactionApi unit test stubs"""

    def setUp(self):
        self.api = EndorseTransactionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transaction_tran_id_resend_post(self):
        """Test case for transaction_tran_id_resend_post

        For Author to resend a particular transaction request  # noqa: E501
        """
        pass

    def test_transactions_conn_id_set_endorser_info_post(self):
        """Test case for transactions_conn_id_set_endorser_info_post

        Set Endorser Info  # noqa: E501
        """
        pass

    def test_transactions_conn_id_set_endorser_role_post(self):
        """Test case for transactions_conn_id_set_endorser_role_post

        Set transaction jobs  # noqa: E501
        """
        pass

    def test_transactions_create_request_post(self):
        """Test case for transactions_create_request_post

        For author to send a transaction request  # noqa: E501
        """
        pass

    def test_transactions_get(self):
        """Test case for transactions_get

        Query transactions  # noqa: E501
        """
        pass

    def test_transactions_tran_id_cancel_post(self):
        """Test case for transactions_tran_id_cancel_post

        For Author to cancel a particular transaction request  # noqa: E501
        """
        pass

    def test_transactions_tran_id_endorse_post(self):
        """Test case for transactions_tran_id_endorse_post

        For Endorser to endorse a particular transaction record  # noqa: E501
        """
        pass

    def test_transactions_tran_id_get(self):
        """Test case for transactions_tran_id_get

        Fetch a single transaction record  # noqa: E501
        """
        pass

    def test_transactions_tran_id_refuse_post(self):
        """Test case for transactions_tran_id_refuse_post

        For Endorser to refuse a particular transaction record  # noqa: E501
        """
        pass

    def test_transactions_tran_id_write_post(self):
        """Test case for transactions_tran_id_write_post

        For Author / Endorser to write an endorsed transaction to the ledger  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
