"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.multitenancy_api import MultitenancyApi  # noqa: E501


class TestMultitenancyApi(unittest.TestCase):
    """MultitenancyApi unit test stubs"""

    def setUp(self):
        self.api = MultitenancyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_multitenancy_wallet_post(self):
        """Test case for multitenancy_wallet_post

        Create a subwallet  # noqa: E501
        """
        pass

    def test_multitenancy_wallet_wallet_id_get(self):
        """Test case for multitenancy_wallet_wallet_id_get

        Get a single subwallet  # noqa: E501
        """
        pass

    def test_multitenancy_wallet_wallet_id_put(self):
        """Test case for multitenancy_wallet_wallet_id_put

        Update a subwallet  # noqa: E501
        """
        pass

    def test_multitenancy_wallet_wallet_id_remove_post(self):
        """Test case for multitenancy_wallet_wallet_id_remove_post

        Remove a subwallet  # noqa: E501
        """
        pass

    def test_multitenancy_wallet_wallet_id_token_post(self):
        """Test case for multitenancy_wallet_wallet_id_token_post

        Get auth token for a subwallet  # noqa: E501
        """
        pass

    def test_multitenancy_wallets_get(self):
        """Test case for multitenancy_wallets_get

        Query subwallets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
