"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.date import Date


class TestDate(unittest.TestCase):
    """Date unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDate(self):
        """Test Date"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Date()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
