"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attach_decorator import AttachDecorator
from openapi_client.model.credential_preview import CredentialPreview
globals()['AttachDecorator'] = AttachDecorator
globals()['CredentialPreview'] = CredentialPreview
from openapi_client.model.credential_offer import CredentialOffer


class TestCredentialOffer(unittest.TestCase):
    """CredentialOffer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialOffer(self):
        """Test CredentialOffer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CredentialOffer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
