"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.schema_input_descriptor import SchemaInputDescriptor
globals()['SchemaInputDescriptor'] = SchemaInputDescriptor
from openapi_client.model.schemas_input_descriptor_filter import SchemasInputDescriptorFilter


class TestSchemasInputDescriptorFilter(unittest.TestCase):
    """SchemasInputDescriptorFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchemasInputDescriptorFilter(self):
        """Test SchemasInputDescriptorFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SchemasInputDescriptorFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
