"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sign_response import SignResponse


class TestSignResponse(unittest.TestCase):
    """SignResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignResponse(self):
        """Test SignResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SignResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
