"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_cred_ex_record_by_format import V20CredExRecordByFormat
from openapi_client.model.v20_cred_issue import V20CredIssue
from openapi_client.model.v20_cred_offer import V20CredOffer
from openapi_client.model.v20_cred_preview import V20CredPreview
from openapi_client.model.v20_cred_proposal import V20CredProposal
from openapi_client.model.v20_cred_request import V20CredRequest
globals()['V20CredExRecordByFormat'] = V20CredExRecordByFormat
globals()['V20CredIssue'] = V20CredIssue
globals()['V20CredOffer'] = V20CredOffer
globals()['V20CredPreview'] = V20CredPreview
globals()['V20CredProposal'] = V20CredProposal
globals()['V20CredRequest'] = V20CredRequest
from openapi_client.model.v20_cred_ex_record import V20CredExRecord


class TestV20CredExRecord(unittest.TestCase):
    """V20CredExRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredExRecord(self):
        """Test V20CredExRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredExRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
