"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.introduction_api import IntroductionApi  # noqa: E501


class TestIntroductionApi(unittest.TestCase):
    """IntroductionApi unit test stubs"""

    def setUp(self):
        self.api = IntroductionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connections_conn_id_start_introduction_post(self):
        """Test case for connections_conn_id_start_introduction_post

        Start an introduction between two connections  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
