"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.transaction_record import TransactionRecord


class TestTransactionRecord(unittest.TestCase):
    """TransactionRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionRecord(self):
        """Test TransactionRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
