"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_cred_filter_indy import V20CredFilterIndy


class TestV20CredFilterIndy(unittest.TestCase):
    """V20CredFilterIndy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredFilterIndy(self):
        """Test V20CredFilterIndy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredFilterIndy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
