"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_rev_reg_entry_value import IndyRevRegEntryValue
globals()['IndyRevRegEntryValue'] = IndyRevRegEntryValue
from openapi_client.model.indy_rev_reg_entry import IndyRevRegEntry


class TestIndyRevRegEntry(unittest.TestCase):
    """IndyRevRegEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyRevRegEntry(self):
        """Test IndyRevRegEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyRevRegEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
