"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.signature_options import SignatureOptions
globals()['SignatureOptions'] = SignatureOptions
from openapi_client.model.signed_doc import SignedDoc


class TestSignedDoc(unittest.TestCase):
    """SignedDoc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignedDoc(self):
        """Test SignedDoc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SignedDoc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
