"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_requested_creds_requested_attr import IndyRequestedCredsRequestedAttr
from openapi_client.model.indy_requested_creds_requested_pred import IndyRequestedCredsRequestedPred
globals()['IndyRequestedCredsRequestedAttr'] = IndyRequestedCredsRequestedAttr
globals()['IndyRequestedCredsRequestedPred'] = IndyRequestedCredsRequestedPred
from openapi_client.model.indy_pres_spec import IndyPresSpec


class TestIndyPresSpec(unittest.TestCase):
    """IndyPresSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyPresSpec(self):
        """Test IndyPresSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyPresSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
