"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_cred_filter import V20CredFilter
from openapi_client.model.v20_cred_preview import V20CredPreview
globals()['V20CredFilter'] = V20CredFilter
globals()['V20CredPreview'] = V20CredPreview
from openapi_client.model.v20_cred_offer_request import V20CredOfferRequest


class TestV20CredOfferRequest(unittest.TestCase):
    """V20CredOfferRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredOfferRequest(self):
        """Test V20CredOfferRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredOfferRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
