"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mediation_create_request import MediationCreateRequest


class TestMediationCreateRequest(unittest.TestCase):
    """MediationCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediationCreateRequest(self):
        """Test MediationCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MediationCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
