"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_proof_req_attr_spec import IndyProofReqAttrSpec
from openapi_client.model.indy_proof_req_pred_spec import IndyProofReqPredSpec
from openapi_client.model.indy_proof_request_non_revoked import IndyProofRequestNonRevoked
globals()['IndyProofReqAttrSpec'] = IndyProofReqAttrSpec
globals()['IndyProofReqPredSpec'] = IndyProofReqPredSpec
globals()['IndyProofRequestNonRevoked'] = IndyProofRequestNonRevoked
from openapi_client.model.indy_proof_request import IndyProofRequest


class TestIndyProofRequest(unittest.TestCase):
    """IndyProofRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyProofRequest(self):
        """Test IndyProofRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyProofRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
