"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_pres_request_by_format import V20PresRequestByFormat
globals()['V20PresRequestByFormat'] = V20PresRequestByFormat
from openapi_client.model.v20_pres_create_request_request import V20PresCreateRequestRequest


class TestV20PresCreateRequestRequest(unittest.TestCase):
    """V20PresCreateRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresCreateRequestRequest(self):
        """Test V20PresCreateRequestRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresCreateRequestRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
