"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_pres_preview import IndyPresPreview
globals()['IndyPresPreview'] = IndyPresPreview
from openapi_client.model.presentation_proposal import PresentationProposal


class TestPresentationProposal(unittest.TestCase):
    """PresentationProposal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPresentationProposal(self):
        """Test PresentationProposal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PresentationProposal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
