"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_cred_info import IndyCredInfo
globals()['IndyCredInfo'] = IndyCredInfo
from openapi_client.model.cred_info_list import CredInfoList


class TestCredInfoList(unittest.TestCase):
    """CredInfoList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredInfoList(self):
        """Test CredInfoList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CredInfoList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
