"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_rev_reg_def_value_public_keys_accum_key import IndyRevRegDefValuePublicKeysAccumKey
globals()['IndyRevRegDefValuePublicKeysAccumKey'] = IndyRevRegDefValuePublicKeysAccumKey
from openapi_client.model.indy_rev_reg_def_value_public_keys import IndyRevRegDefValuePublicKeys


class TestIndyRevRegDefValuePublicKeys(unittest.TestCase):
    """IndyRevRegDefValuePublicKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyRevRegDefValuePublicKeys(self):
        """Test IndyRevRegDefValuePublicKeys"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyRevRegDefValuePublicKeys()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
