"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.jsonld_api import JsonldApi  # noqa: E501


class TestJsonldApi(unittest.TestCase):
    """JsonldApi unit test stubs"""

    def setUp(self):
        self.api = JsonldApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jsonld_sign_post(self):
        """Test case for jsonld_sign_post

        Sign a JSON-LD structure and return it  # noqa: E501
        """
        pass

    def test_jsonld_verify_post(self):
        """Test case for jsonld_verify_post

        Verify a JSON-LD structure.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
