"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dif_proof_request import DIFProofRequest
from openapi_client.model.indy_proof_request import IndyProofRequest
globals()['DIFProofRequest'] = DIFProofRequest
globals()['IndyProofRequest'] = IndyProofRequest
from openapi_client.model.v20_pres_request_by_format import V20PresRequestByFormat


class TestV20PresRequestByFormat(unittest.TestCase):
    """V20PresRequestByFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresRequestByFormat(self):
        """Test V20PresRequestByFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresRequestByFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
