"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_cred_info import IndyCredInfo
from openapi_client.model.indy_non_revocation_interval import IndyNonRevocationInterval
globals()['IndyCredInfo'] = IndyCredInfo
globals()['IndyNonRevocationInterval'] = IndyNonRevocationInterval
from openapi_client.model.indy_cred_precis import IndyCredPrecis


class TestIndyCredPrecis(unittest.TestCase):
    """IndyCredPrecis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyCredPrecis(self):
        """Test IndyCredPrecis"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyCredPrecis()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
