"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.presentation_definition import PresentationDefinition
globals()['PresentationDefinition'] = PresentationDefinition
from openapi_client.model.dif_pres_spec import DIFPresSpec


class TestDIFPresSpec(unittest.TestCase):
    """DIFPresSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDIFPresSpec(self):
        """Test DIFPresSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DIFPresSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
