"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_cred_ex_record import V20CredExRecord
from openapi_client.model.v20_cred_ex_record_indy import V20CredExRecordIndy
from openapi_client.model.v20_cred_ex_record_ld_proof import V20CredExRecordLDProof
globals()['V20CredExRecord'] = V20CredExRecord
globals()['V20CredExRecordIndy'] = V20CredExRecordIndy
globals()['V20CredExRecordLDProof'] = V20CredExRecordLDProof
from openapi_client.model.v20_cred_ex_record_detail import V20CredExRecordDetail


class TestV20CredExRecordDetail(unittest.TestCase):
    """V20CredExRecordDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredExRecordDetail(self):
        """Test V20CredExRecordDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredExRecordDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
