"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_key_correctness_proof import IndyKeyCorrectnessProof


class TestIndyKeyCorrectnessProof(unittest.TestCase):
    """IndyKeyCorrectnessProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyKeyCorrectnessProof(self):
        """Test IndyKeyCorrectnessProof"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyKeyCorrectnessProof()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
