"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_proof_proof_aggregated_proof import IndyProofProofAggregatedProof
from openapi_client.model.indy_proof_proof_proofs_proof import IndyProofProofProofsProof
globals()['IndyProofProofAggregatedProof'] = IndyProofProofAggregatedProof
globals()['IndyProofProofProofsProof'] = IndyProofProofProofsProof
from openapi_client.model.indy_proof_proof import IndyProofProof


class TestIndyProofProof(unittest.TestCase):
    """IndyProofProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyProofProof(self):
        """Test IndyProofProof"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyProofProof()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
