"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.raw_encoded import RawEncoded


class TestRawEncoded(unittest.TestCase):
    """RawEncoded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRawEncoded(self):
        """Test RawEncoded"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RawEncoded()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
