"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.keylist_query_paginate import KeylistQueryPaginate
globals()['KeylistQueryPaginate'] = KeylistQueryPaginate
from openapi_client.model.keylist_query import KeylistQuery


class TestKeylistQuery(unittest.TestCase):
    """KeylistQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeylistQuery(self):
        """Test KeylistQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KeylistQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
