"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dif_pres_spec import DIFPresSpec
from openapi_client.model.indy_pres_spec import IndyPresSpec
globals()['DIFPresSpec'] = DIFPresSpec
globals()['IndyPresSpec'] = IndyPresSpec
from openapi_client.model.v20_pres_spec_by_format_request import V20PresSpecByFormatRequest


class TestV20PresSpecByFormatRequest(unittest.TestCase):
    """V20PresSpecByFormatRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresSpecByFormatRequest(self):
        """Test V20PresSpecByFormatRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresSpecByFormatRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
