"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cred_def_value_primary import CredDefValuePrimary
from openapi_client.model.cred_def_value_revocation import CredDefValueRevocation
globals()['CredDefValuePrimary'] = CredDefValuePrimary
globals()['CredDefValueRevocation'] = CredDefValueRevocation
from openapi_client.model.cred_def_value import CredDefValue


class TestCredDefValue(unittest.TestCase):
    """CredDefValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredDefValue(self):
        """Test CredDefValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CredDefValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
