"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ping_request import PingRequest


class TestPingRequest(unittest.TestCase):
    """PingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPingRequest(self):
        """Test PingRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PingRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
