"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_rev_reg_def_value_public_keys import IndyRevRegDefValuePublicKeys
globals()['IndyRevRegDefValuePublicKeys'] = IndyRevRegDefValuePublicKeys
from openapi_client.model.indy_rev_reg_def_value import IndyRevRegDefValue


class TestIndyRevRegDefValue(unittest.TestCase):
    """IndyRevRegDefValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyRevRegDefValue(self):
        """Test IndyRevRegDefValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyRevRegDefValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
