"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.claim_format import ClaimFormat


class TestClaimFormat(unittest.TestCase):
    """ClaimFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClaimFormat(self):
        """Test ClaimFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClaimFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
