"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.credential_offer import CredentialOffer
from openapi_client.model.credential_proposal import CredentialProposal
from openapi_client.model.indy_cred_abstract import IndyCredAbstract
from openapi_client.model.indy_cred_info import IndyCredInfo
from openapi_client.model.indy_cred_request import IndyCredRequest
from openapi_client.model.indy_credential import IndyCredential
globals()['CredentialOffer'] = CredentialOffer
globals()['CredentialProposal'] = CredentialProposal
globals()['IndyCredAbstract'] = IndyCredAbstract
globals()['IndyCredInfo'] = IndyCredInfo
globals()['IndyCredRequest'] = IndyCredRequest
globals()['IndyCredential'] = IndyCredential
from openapi_client.model.v10_credential_exchange import V10CredentialExchange


class TestV10CredentialExchange(unittest.TestCase):
    """V10CredentialExchange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10CredentialExchange(self):
        """Test V10CredentialExchange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10CredentialExchange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
