"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.signature_options import SignatureOptions
globals()['SignatureOptions'] = SignatureOptions
from openapi_client.model.doc import Doc


class TestDoc(unittest.TestCase):
    """Doc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoc(self):
        """Test Doc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Doc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
