"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_pres import V20Pres
from openapi_client.model.v20_pres_ex_record_by_format import V20PresExRecordByFormat
from openapi_client.model.v20_pres_proposal import V20PresProposal
from openapi_client.model.v20_pres_request import V20PresRequest
globals()['V20Pres'] = V20Pres
globals()['V20PresExRecordByFormat'] = V20PresExRecordByFormat
globals()['V20PresProposal'] = V20PresProposal
globals()['V20PresRequest'] = V20PresRequest
from openapi_client.model.v20_pres_ex_record import V20PresExRecord


class TestV20PresExRecord(unittest.TestCase):
    """V20PresExRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20PresExRecord(self):
        """Test V20PresExRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20PresExRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
