"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.constraints import Constraints
from openapi_client.model.schemas_input_descriptor_filter import SchemasInputDescriptorFilter
globals()['Constraints'] = Constraints
globals()['SchemasInputDescriptorFilter'] = SchemasInputDescriptorFilter
from openapi_client.model.input_descriptors import InputDescriptors


class TestInputDescriptors(unittest.TestCase):
    """InputDescriptors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputDescriptors(self):
        """Test InputDescriptors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InputDescriptors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
