"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.filter import Filter
globals()['Filter'] = Filter
from openapi_client.model.dif_field import DIFField


class TestDIFField(unittest.TestCase):
    """DIFField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDIFField(self):
        """Test DIFField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DIFField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
