"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dif_options import DIFOptions


class TestDIFOptions(unittest.TestCase):
    """DIFOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDIFOptions(self):
        """Test DIFOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DIFOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
