"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v10_credential_issue_request import V10CredentialIssueRequest


class TestV10CredentialIssueRequest(unittest.TestCase):
    """V10CredentialIssueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10CredentialIssueRequest(self):
        """Test V10CredentialIssueRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10CredentialIssueRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
