"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_cred_store_request import V20CredStoreRequest


class TestV20CredStoreRequest(unittest.TestCase):
    """V20CredStoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredStoreRequest(self):
        """Test V20CredStoreRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredStoreRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
