"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.claim_format import ClaimFormat
from openapi_client.model.input_descriptors import InputDescriptors
from openapi_client.model.submission_requirements import SubmissionRequirements
globals()['ClaimFormat'] = ClaimFormat
globals()['InputDescriptors'] = InputDescriptors
globals()['SubmissionRequirements'] = SubmissionRequirements
from openapi_client.model.presentation_definition import PresentationDefinition


class TestPresentationDefinition(unittest.TestCase):
    """PresentationDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPresentationDefinition(self):
        """Test PresentationDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PresentationDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
