"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attach_decorator import AttachDecorator
from openapi_client.model.v20_cred_format import V20CredFormat
from openapi_client.model.v20_cred_preview import V20CredPreview
globals()['AttachDecorator'] = AttachDecorator
globals()['V20CredFormat'] = V20CredFormat
globals()['V20CredPreview'] = V20CredPreview
from openapi_client.model.v20_cred_offer import V20CredOffer


class TestV20CredOffer(unittest.TestCase):
    """V20CredOffer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredOffer(self):
        """Test V20CredOffer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredOffer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
