"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.raw_encoded import RawEncoded
globals()['RawEncoded'] = RawEncoded
from openapi_client.model.indy_proof_requested_proof_revealed_attr_group import IndyProofRequestedProofRevealedAttrGroup


class TestIndyProofRequestedProofRevealedAttrGroup(unittest.TestCase):
    """IndyProofRequestedProofRevealedAttrGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyProofRequestedProofRevealedAttrGroup(self):
        """Test IndyProofRequestedProofRevealedAttrGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyProofRequestedProofRevealedAttrGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
