"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_non_revoc_proof import IndyNonRevocProof
from openapi_client.model.indy_primary_proof import IndyPrimaryProof
globals()['IndyNonRevocProof'] = IndyNonRevocProof
globals()['IndyPrimaryProof'] = IndyPrimaryProof
from openapi_client.model.indy_proof_proof_proofs_proof import IndyProofProofProofsProof


class TestIndyProofProofProofsProof(unittest.TestCase):
    """IndyProofProofProofsProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyProofProofProofsProof(self):
        """Test IndyProofProofProofsProof"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyProofProofProofsProof()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
