"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v20_cred_format import V20CredFormat


class TestV20CredFormat(unittest.TestCase):
    """V20CredFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredFormat(self):
        """Test V20CredFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
