"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.linked_data_proof import LinkedDataProof
globals()['LinkedDataProof'] = LinkedDataProof
from openapi_client.model.credential import Credential


class TestCredential(unittest.TestCase):
    """Credential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredential(self):
        """Test Credential"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Credential()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
