"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_ge_proof_pred import IndyGEProofPred


class TestIndyGEProofPred(unittest.TestCase):
    """IndyGEProofPred unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyGEProofPred(self):
        """Test IndyGEProofPred"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyGEProofPred()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
