"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_proof_request import IndyProofRequest
globals()['IndyProofRequest'] = IndyProofRequest
from openapi_client.model.v10_presentation_send_request_request import V10PresentationSendRequestRequest


class TestV10PresentationSendRequestRequest(unittest.TestCase):
    """V10PresentationSendRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10PresentationSendRequestRequest(self):
        """Test V10PresentationSendRequestRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10PresentationSendRequestRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
