"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_key_correctness_proof import IndyKeyCorrectnessProof
globals()['IndyKeyCorrectnessProof'] = IndyKeyCorrectnessProof
from openapi_client.model.indy_cred_abstract import IndyCredAbstract


class TestIndyCredAbstract(unittest.TestCase):
    """IndyCredAbstract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyCredAbstract(self):
        """Test IndyCredAbstract"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyCredAbstract()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
