"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_eq_proof import IndyEQProof
from openapi_client.model.indy_ge_proof import IndyGEProof
globals()['IndyEQProof'] = IndyEQProof
globals()['IndyGEProof'] = IndyGEProof
from openapi_client.model.indy_primary_proof import IndyPrimaryProof


class TestIndyPrimaryProof(unittest.TestCase):
    """IndyPrimaryProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyPrimaryProof(self):
        """Test IndyPrimaryProof"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyPrimaryProof()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
