"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.connection_invitation import ConnectionInvitation


class TestConnectionInvitation(unittest.TestCase):
    """ConnectionInvitation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionInvitation(self):
        """Test ConnectionInvitation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectionInvitation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
