"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.conn_record import ConnRecord


class TestConnRecord(unittest.TestCase):
    """ConnRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnRecord(self):
        """Test ConnRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
