"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v10_credential_problem_report_request import V10CredentialProblemReportRequest


class TestV10CredentialProblemReportRequest(unittest.TestCase):
    """V10CredentialProblemReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV10CredentialProblemReportRequest(self):
        """Test V10CredentialProblemReportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V10CredentialProblemReportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
