"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.did_create_options import DIDCreateOptions
globals()['DIDCreateOptions'] = DIDCreateOptions
from openapi_client.model.did_create import DIDCreate


class TestDIDCreate(unittest.TestCase):
    """DIDCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDIDCreate(self):
        """Test DIDCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DIDCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
