"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.issuer_cred_rev_record import IssuerCredRevRecord


class TestIssuerCredRevRecord(unittest.TestCase):
    """IssuerCredRevRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssuerCredRevRecord(self):
        """Test IssuerCredRevRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssuerCredRevRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
