"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attach_decorator_data_jws import AttachDecoratorDataJWS
globals()['AttachDecoratorDataJWS'] = AttachDecoratorDataJWS
from openapi_client.model.attach_decorator_data import AttachDecoratorData


class TestAttachDecoratorData(unittest.TestCase):
    """AttachDecoratorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachDecoratorData(self):
        """Test AttachDecoratorData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachDecoratorData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
