"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.basicmessage_api import BasicmessageApi  # noqa: E501


class TestBasicmessageApi(unittest.TestCase):
    """BasicmessageApi unit test stubs"""

    def setUp(self):
        self.api = BasicmessageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connections_conn_id_send_message_post(self):
        """Test case for connections_conn_id_send_message_post

        Send a basic message to a connection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
