"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.invitation_message import InvitationMessage
globals()['InvitationMessage'] = InvitationMessage
from openapi_client.model.invitation_record import InvitationRecord


class TestInvitationRecord(unittest.TestCase):
    """InvitationRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitationRecord(self):
        """Test InvitationRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvitationRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
