"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_attr_value import IndyAttrValue
globals()['IndyAttrValue'] = IndyAttrValue
from openapi_client.model.indy_credential import IndyCredential


class TestIndyCredential(unittest.TestCase):
    """IndyCredential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyCredential(self):
        """Test IndyCredential"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyCredential()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
