"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_pres_attr_spec import IndyPresAttrSpec


class TestIndyPresAttrSpec(unittest.TestCase):
    """IndyPresAttrSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyPresAttrSpec(self):
        """Test IndyPresAttrSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyPresAttrSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
