"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.schema_send_request import SchemaSendRequest


class TestSchemaSendRequest(unittest.TestCase):
    """SchemaSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchemaSendRequest(self):
        """Test SchemaSendRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SchemaSendRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
