"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attach_decorator import AttachDecorator
globals()['AttachDecorator'] = AttachDecorator
from openapi_client.model.invitation_message import InvitationMessage


class TestInvitationMessage(unittest.TestCase):
    """InvitationMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitationMessage(self):
        """Test InvitationMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvitationMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
