"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_ge_proof_pred import IndyGEProofPred
globals()['IndyGEProofPred'] = IndyGEProofPred
from openapi_client.model.indy_ge_proof import IndyGEProof


class TestIndyGEProof(unittest.TestCase):
    """IndyGEProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyGEProof(self):
        """Test IndyGEProof"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyGEProof()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
