"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.credential import Credential
from openapi_client.model.ld_proof_vc_detail_options import LDProofVCDetailOptions
globals()['Credential'] = Credential
globals()['LDProofVCDetailOptions'] = LDProofVCDetailOptions
from openapi_client.model.ld_proof_vc_detail import LDProofVCDetail


class TestLDProofVCDetail(unittest.TestCase):
    """LDProofVCDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLDProofVCDetail(self):
        """Test LDProofVCDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LDProofVCDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
