"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dif_field import DIFField
from openapi_client.model.dif_holder import DIFHolder
globals()['DIFField'] = DIFField
globals()['DIFHolder'] = DIFHolder
from openapi_client.model.constraints import Constraints


class TestConstraints(unittest.TestCase):
    """Constraints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConstraints(self):
        """Test Constraints"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Constraints()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
