"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_proof_identifier import IndyProofIdentifier
from openapi_client.model.indy_proof_proof import IndyProofProof
from openapi_client.model.indy_proof_requested_proof import IndyProofRequestedProof
globals()['IndyProofIdentifier'] = IndyProofIdentifier
globals()['IndyProofProof'] = IndyProofProof
globals()['IndyProofRequestedProof'] = IndyProofRequestedProof
from openapi_client.model.indy_proof import IndyProof


class TestIndyProof(unittest.TestCase):
    """IndyProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyProof(self):
        """Test IndyProof"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyProof()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
