"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.indy_proof_req_attr_spec_non_revoked import IndyProofReqAttrSpecNonRevoked


class TestIndyProofReqAttrSpecNonRevoked(unittest.TestCase):
    """IndyProofReqAttrSpecNonRevoked unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndyProofReqAttrSpecNonRevoked(self):
        """Test IndyProofReqAttrSpecNonRevoked"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IndyProofReqAttrSpecNonRevoked()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
