"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attach_decorator import AttachDecorator
from openapi_client.model.v20_cred_format import V20CredFormat
globals()['AttachDecorator'] = AttachDecorator
globals()['V20CredFormat'] = V20CredFormat
from openapi_client.model.v20_cred_request import V20CredRequest


class TestV20CredRequest(unittest.TestCase):
    """V20CredRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20CredRequest(self):
        """Test V20CredRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20CredRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
