"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.rev_regs_created import RevRegsCreated


class TestRevRegsCreated(unittest.TestCase):
    """RevRegsCreated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRevRegsCreated(self):
        """Test RevRegsCreated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RevRegsCreated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
