"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.attach_decorator import AttachDecorator
from openapi_client.model.v20_pres_format import V20PresFormat
globals()['AttachDecorator'] = AttachDecorator
globals()['V20PresFormat'] = V20PresFormat
from openapi_client.model.v20_pres import V20Pres


class TestV20Pres(unittest.TestCase):
    """V20Pres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV20Pres(self):
        """Test V20Pres"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V20Pres()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
