# coding: utf-8

"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.action_menu_api import router as ActionMenuApiRouter
from openapi_server.apis.basicmessage_api import router as BasicmessageApiRouter
from openapi_server.apis.connection_api import router as ConnectionApiRouter
from openapi_server.apis.credential_definition_api import router as CredentialDefinitionApiRouter
from openapi_server.apis.credentials_api import router as CredentialsApiRouter
from openapi_server.apis.did_exchange_api import router as DidExchangeApiRouter
from openapi_server.apis.endorse_transaction_api import router as EndorseTransactionApiRouter
from openapi_server.apis.introduction_api import router as IntroductionApiRouter
from openapi_server.apis.issue_credential_v1_0_api import router as IssueCredentialV10ApiRouter
from openapi_server.apis.issue_credential_v2_0_api import router as IssueCredentialV20ApiRouter
from openapi_server.apis.jsonld_api import router as JsonldApiRouter
from openapi_server.apis.ledger_api import router as LedgerApiRouter
from openapi_server.apis.mediation_api import router as MediationApiRouter
from openapi_server.apis.multitenancy_api import router as MultitenancyApiRouter
from openapi_server.apis.out_of_band_api import router as OutOfBandApiRouter
from openapi_server.apis.present_proof_v1_0_api import router as PresentProofV10ApiRouter
from openapi_server.apis.present_proof_v2_0_api import router as PresentProofV20ApiRouter
from openapi_server.apis.resolver_api import router as ResolverApiRouter
from openapi_server.apis.revocation_api import router as RevocationApiRouter
from openapi_server.apis.schema_api import router as SchemaApiRouter
from openapi_server.apis.server_api import router as ServerApiRouter
from openapi_server.apis.trustping_api import router as TrustpingApiRouter
from openapi_server.apis.wallet_api import router as WalletApiRouter

app = FastAPI(
    title="Aries Cloud Agent",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="v0.7.2",
)

app.include_router(ActionMenuApiRouter)
app.include_router(BasicmessageApiRouter)
app.include_router(ConnectionApiRouter)
app.include_router(CredentialDefinitionApiRouter)
app.include_router(CredentialsApiRouter)
app.include_router(DidExchangeApiRouter)
app.include_router(EndorseTransactionApiRouter)
app.include_router(IntroductionApiRouter)
app.include_router(IssueCredentialV10ApiRouter)
app.include_router(IssueCredentialV20ApiRouter)
app.include_router(JsonldApiRouter)
app.include_router(LedgerApiRouter)
app.include_router(MediationApiRouter)
app.include_router(MultitenancyApiRouter)
app.include_router(OutOfBandApiRouter)
app.include_router(PresentProofV10ApiRouter)
app.include_router(PresentProofV20ApiRouter)
app.include_router(ResolverApiRouter)
app.include_router(RevocationApiRouter)
app.include_router(SchemaApiRouter)
app.include_router(ServerApiRouter)
app.include_router(TrustpingApiRouter)
app.include_router(WalletApiRouter)
