# coding: utf-8

"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.2
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from acapy_wrapper.apis.action_menu_api import router as ActionMenuApiRouter
from acapy_wrapper.apis.basicmessage_api import router as BasicmessageApiRouter
from acapy_wrapper.apis.connection_api import router as ConnectionApiRouter
from acapy_wrapper.apis.credential_definition_api import router as CredentialDefinitionApiRouter
from acapy_wrapper.apis.credentials_api import router as CredentialsApiRouter
from acapy_wrapper.apis.did_exchange_api import router as DidExchangeApiRouter
from acapy_wrapper.apis.endorse_transaction_api import router as EndorseTransactionApiRouter
from acapy_wrapper.apis.introduction_api import router as IntroductionApiRouter
from acapy_wrapper.apis.issue_credential_v1_0_api import router as IssueCredentialV10ApiRouter
from acapy_wrapper.apis.issue_credential_v2_0_api import router as IssueCredentialV20ApiRouter
from acapy_wrapper.apis.jsonld_api import router as JsonldApiRouter
from acapy_wrapper.apis.ledger_api import router as LedgerApiRouter
from acapy_wrapper.apis.mediation_api import router as MediationApiRouter
from acapy_wrapper.apis.multitenancy_api import router as MultitenancyApiRouter
from acapy_wrapper.apis.out_of_band_api import router as OutOfBandApiRouter
from acapy_wrapper.apis.present_proof_v1_0_api import router as PresentProofV10ApiRouter
from acapy_wrapper.apis.present_proof_v2_0_api import router as PresentProofV20ApiRouter
from acapy_wrapper.apis.resolver_api import router as ResolverApiRouter
from acapy_wrapper.apis.revocation_api import router as RevocationApiRouter
from acapy_wrapper.apis.schema_api import router as SchemaApiRouter
from acapy_wrapper.apis.server_api import router as ServerApiRouter
from acapy_wrapper.apis.trustping_api import router as TrustpingApiRouter
from acapy_wrapper.apis.wallet_api import router as WalletApiRouter

app = FastAPI(
    title="Aries Cloud Agent",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="v0.7.2",
)

app.include_router(ActionMenuApiRouter)
app.include_router(BasicmessageApiRouter)
app.include_router(ConnectionApiRouter)
app.include_router(CredentialDefinitionApiRouter)
app.include_router(CredentialsApiRouter)
app.include_router(DidExchangeApiRouter)
app.include_router(EndorseTransactionApiRouter)
app.include_router(IntroductionApiRouter)
app.include_router(IssueCredentialV10ApiRouter)
app.include_router(IssueCredentialV20ApiRouter)
app.include_router(JsonldApiRouter)
app.include_router(LedgerApiRouter)
app.include_router(MediationApiRouter)
# app.include_router(MultitenancyApiRouter)
app.include_router(OutOfBandApiRouter)
app.include_router(PresentProofV10ApiRouter)
app.include_router(PresentProofV20ApiRouter)
app.include_router(ResolverApiRouter)
app.include_router(RevocationApiRouter)
app.include_router(SchemaApiRouter)
app.include_router(ServerApiRouter)
app.include_router(TrustpingApiRouter)
app.include_router(WalletApiRouter)
